- name: play level variables
  hosts: all
  vars:
   URL: play.ansible.variable
  tasks:
    - name: print ansible play lavel variable
      ansible.builtin.debug:
       msg: url = {{URL}}

## if the variable declear in play level it is accesible in all tasks.

- name: play level variable from the file
  hosts: all
  vars_files: 
    vars_sample.yml
## if Variable files is at different location then specify the complete path to access the file variables
  tasks:
   - name: print play level variable from file
     ansible.builtin.debug:
      msg: url = {{URL}} 

- name: task level variables 
  hosts: all
  tasks: 
   - name: print the task level variable
     ansible.builtin.debug:
       msg: url = {{URL}} 
     vars: 
       URL: example.tasklevel.variable 

## if variable is declear at task level then it is accesiable in task only. 