- name: Anisble Filters
  hosts: localhost
  vars:
    a: abc
  tasks:
    - name: Convert Case of String
      debug:
        msg: "{{a | upper}}"
    - name: URL
      debug:
        msg: HOST = {{ "http://user:password@www.acme.com:9000/dir/index.html?query=term#fragment" | urlsplit('hostname') }}
