- name: Install Nginx
  ansible.builtin.yum:
    name: nginx
    state: installed

- name: Download and Extract Frontend
  include_role:
    name: common
    tasks_from: download
  vars:
    APP_USER: root
    APP_LOCATION: /usr/share/nginx/html

#- name: Cleanup Old HTML Content
#  ansible.builtin.file:
#    path: /usr/share/nginx/html
#    state: absent

#- name: Copy the frontend content to nginx path
#  ansible.builtin.copy:
#    src: /tmp/frontend-main/static/
#    dest: /usr/share/nginx/html/
#    remote_src: yes
# Note: IN src and dest, ending / is very important when you are copying directories

- name: Copy RoboShop Configuration
  ansible.builtin.template:
    src: roboshop.conf
    dest: /etc/nginx/default.d/roboshop.conf
  #notify: Restart Nginx

- name: Copy Nginx Configuration
  ansible.builtin.template:
    src: nginx.conf
    dest: /etc/nginx/nginx.conf
  #notify: Restart Nginx

- name: Start Nginx Service
  ignore_errors: "{{CHECK_MODE}}"
  ansible.builtin.systemd:
    name: nginx
    state: started
    enabled: yes
  when: ENV != "ENV"

- name: Configure Filebeat
  ansible.builtin.include_role:
    name: elk
    tasks_from: filebeat

- name: Install Prometheus Node exporter
  ansible.builtin.include_role:
    name: prometheus
    tasks_from: node-exporter

