- name: Copy LogStash Configuration
  template:
    src: logstash.conf
    dest: /etc/logstash/conf.d/logstash.conf

- name: Restart LogStash
  systemd:
    name: logstash
    state: restarted

- name: Wait for LogStash to Open the Port
  wait_for:
    port: 5044
    delay: 60
    timeout: 120

