- name: Add Application User
  ansible.builtin.user:
    name: roboshop
    comment: RoboShop Project Application User
  register: APP_USER_REGISTER

- name: Cleanup Old Content
  ansible.builtin.file:
    path: "{{APP_LOCATION}}"
    state: absent

############### Download from GitHub
### As per standard process we download the software from a release rather than
### from git repo. Hence we are commenting and moving with other steps which is
### to download from Nexus repo.

#- name: Download and Extract {{COMPONENT}}
#  ansible.builtin.unarchive:
#    src: https://github.com/roboshop-devops-project/{{COMPONENT}}/archive/main.zip
#    dest: /tmp
#    remote_src: yes

#- name: Copy App Content
#  become_user: "{{APP_USER}}"
#  ansible.builtin.copy:
#    dest: "{{APP_LOCATION}}"
#    src: /tmp/{{COMPONENT}}-main/
#    remote_src: yes

############### Download from Nexus
- name: Create App Location
  ansible.builtin.file:
    path: "{{APP_LOCATION}}"
    state: directory
  become_user: "{{APP_USER}}"

- name: Download and Extract {{COMPONENT}}
  ansible.builtin.unarchive:
    src: http://nexus.roboshop.internal:8081/repository/{{COMPONENT}}/{{COMPONENT}}-{{APP_VERSION}}.zip
    dest: "{{APP_LOCATION}}"
    remote_src: yes
  become_user: "{{APP_USER}}"

- name: Download DocumentDB PEM File
  when: MONGO_CONNECT is defined
  become_user: "{{APP_USER}}"
  get_url:
    url: https://s3.amazonaws.com/rds-downloads/rds-combined-ca-bundle.pem
    dest: "{{APP_LOCATION}}/rds-combined-ca-bundle.pem"


